// Code generated by mockery v2.50.0. DO NOT EDIT.

package inframocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IAuthHandlerHttp is an autogenerated mock type for the IAuthHandlerHttp type
type IAuthHandlerHttp struct {
	mock.Mock
}

// Auth provides a mock function with given fields: c
func (_m *IAuthHandlerHttp) Auth(c *gin.Context) {
	_m.Called(c)
}

// Callback provides a mock function with given fields: c
func (_m *IAuthHandlerHttp) Callback(c *gin.Context) {
	_m.Called(c)
}

// IsLoggedIn provides a mock function with given fields: c
func (_m *IAuthHandlerHttp) IsLoggedIn(c *gin.Context) {
	_m.Called(c)
}

// Logout provides a mock function with given fields: c
func (_m *IAuthHandlerHttp) Logout(c *gin.Context) {
	_m.Called(c)
}

// ValidateToken provides a mock function with given fields: c
func (_m *IAuthHandlerHttp) ValidateToken(c *gin.Context) {
	_m.Called(c)
}

// NewIAuthHandlerHttp creates a new instance of IAuthHandlerHttp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthHandlerHttp(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthHandlerHttp {
	mock := &IAuthHandlerHttp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
