// Code generated by mockery v2.50.0. DO NOT EDIT.

package inframocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// TenantHandlerHttpInterface is an autogenerated mock type for the TenantHandlerHttpInterface type
type TenantHandlerHttpInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *TenantHandlerHttpInterface) Create(c *gin.Context) {
	_m.Called(c)
}

// Delete provides a mock function with given fields: c
func (_m *TenantHandlerHttpInterface) Delete(c *gin.Context) {
	_m.Called(c)
}

// Get provides a mock function with given fields: c
func (_m *TenantHandlerHttpInterface) Get(c *gin.Context) {
	_m.Called(c)
}

// GetByFilterMany provides a mock function with given fields: c
func (_m *TenantHandlerHttpInterface) GetByFilterMany(c *gin.Context) {
	_m.Called(c)
}

// GetByFilterOne provides a mock function with given fields: c
func (_m *TenantHandlerHttpInterface) GetByFilterOne(c *gin.Context) {
	_m.Called(c)
}

// GetById provides a mock function with given fields: c
func (_m *TenantHandlerHttpInterface) GetById(c *gin.Context) {
	_m.Called(c)
}

// Update provides a mock function with given fields: c
func (_m *TenantHandlerHttpInterface) Update(c *gin.Context) {
	_m.Called(c)
}

// NewTenantHandlerHttpInterface creates a new instance of TenantHandlerHttpInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantHandlerHttpInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantHandlerHttpInterface {
	mock := &TenantHandlerHttpInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
