// Code generated by mockery v2.50.0. DO NOT EDIT.

package inframocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// WalletHandlerHttpInterface is an autogenerated mock type for the WalletHandlerHttpInterface type
type WalletHandlerHttpInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *WalletHandlerHttpInterface) Create(c *gin.Context) {
	_m.Called(c)
}

// Delete provides a mock function with given fields: c
func (_m *WalletHandlerHttpInterface) Delete(c *gin.Context) {
	_m.Called(c)
}

// Get provides a mock function with given fields: c
func (_m *WalletHandlerHttpInterface) Get(c *gin.Context) {
	_m.Called(c)
}

// GetByFilterMany provides a mock function with given fields: c
func (_m *WalletHandlerHttpInterface) GetByFilterMany(c *gin.Context) {
	_m.Called(c)
}

// GetByFilterOne provides a mock function with given fields: c
func (_m *WalletHandlerHttpInterface) GetByFilterOne(c *gin.Context) {
	_m.Called(c)
}

// GetWalletByIdAndUserID provides a mock function with given fields: c
func (_m *WalletHandlerHttpInterface) GetWalletByIdAndUserID(c *gin.Context) {
	_m.Called(c)
}

// Update provides a mock function with given fields: c
func (_m *WalletHandlerHttpInterface) Update(c *gin.Context) {
	_m.Called(c)
}

// NewWalletHandlerHttpInterface creates a new instance of WalletHandlerHttpInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletHandlerHttpInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletHandlerHttpInterface {
	mock := &WalletHandlerHttpInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
