// Code generated by mockery v2.50.0. DO NOT EDIT.

package coremocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/Tomelin/financial-management-backend/internal/core/entity"
)

// IPlan is an autogenerated mock type for the IPlan type
type IPlan struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *IPlan) Create(_a0 *entity.PlanResponse) (*entity.PlanResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.PlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.PlanResponse) (*entity.PlanResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.PlanResponse) *entity.PlanResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.PlanResponse) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *IPlan) Delete(id *string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with no fields
func (_m *IPlan) Get() ([]entity.PlanResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []entity.PlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.PlanResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.PlanResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByFilterMany provides a mock function with given fields: key, value
func (_m *IPlan) GetByFilterMany(key string, value *string) ([]entity.PlanResponse, error) {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for GetByFilterMany")
	}

	var r0 []entity.PlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *string) ([]entity.PlanResponse, error)); ok {
		return rf(key, value)
	}
	if rf, ok := ret.Get(0).(func(string, *string) []entity.PlanResponse); ok {
		r0 = rf(key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *string) error); ok {
		r1 = rf(key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByFilterOne provides a mock function with given fields: key, value
func (_m *IPlan) GetByFilterOne(key string, value *string) (*entity.PlanResponse, error) {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for GetByFilterOne")
	}

	var r0 *entity.PlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *string) (*entity.PlanResponse, error)); ok {
		return rf(key, value)
	}
	if rf, ok := ret.Get(0).(func(string, *string) *entity.PlanResponse); ok {
		r0 = rf(key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *string) error); ok {
		r1 = rf(key, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *IPlan) GetById(id *string) (*entity.PlanResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *entity.PlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) (*entity.PlanResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(*string) *entity.PlanResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: data
func (_m *IPlan) Update(data *entity.PlanResponse) (*entity.PlanResponse, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.PlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.PlanResponse) (*entity.PlanResponse, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func(*entity.PlanResponse) *entity.PlanResponse); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.PlanResponse) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPlan creates a new instance of IPlan. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPlan(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPlan {
	mock := &IPlan{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
