// Code generated by mockery v2.50.0. DO NOT EDIT.

package coremocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/Tomelin/financial-management-backend/internal/core/entity"
)

// ITenantRepo is an autogenerated mock type for the ITenantRepo type
type ITenantRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *ITenantRepo) Create(_a0 *entity.TenantResponse) (*entity.TenantResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.TenantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.TenantResponse) (*entity.TenantResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entity.TenantResponse) *entity.TenantResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TenantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.TenantResponse) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ITenantRepo) Delete(id *string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with no fields
func (_m *ITenantRepo) Get() ([]entity.TenantResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []entity.TenantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.TenantResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.TenantResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TenantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByFilterMany provides a mock function with given fields: ctx, filter
func (_m *ITenantRepo) GetByFilterMany(ctx context.Context, filter []entity.QueryDB) ([]entity.TenantResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetByFilterMany")
	}

	var r0 []entity.TenantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.QueryDB) ([]entity.TenantResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.QueryDB) []entity.TenantResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TenantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.QueryDB) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByFilterOne provides a mock function with given fields: ctx, filter
func (_m *ITenantRepo) GetByFilterOne(ctx context.Context, filter []entity.QueryDB) (*entity.TenantResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetByFilterOne")
	}

	var r0 *entity.TenantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entity.QueryDB) (*entity.TenantResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entity.QueryDB) *entity.TenantResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TenantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entity.QueryDB) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *ITenantRepo) GetById(id *string) (*entity.TenantResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *entity.TenantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) (*entity.TenantResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(*string) *entity.TenantResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TenantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlan provides a mock function with given fields: id
func (_m *ITenantRepo) GetPlan(id *string) (*entity.PlanResponse, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetPlan")
	}

	var r0 *entity.PlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*string) (*entity.PlanResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(*string) *entity.PlanResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPlan provides a mock function with given fields: id, plan
func (_m *ITenantRepo) SetPlan(id *string, plan *entity.PlanResponse) error {
	ret := _m.Called(id, plan)

	if len(ret) == 0 {
		panic("no return value specified for SetPlan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*string, *entity.PlanResponse) error); ok {
		r0 = rf(id, plan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: data
func (_m *ITenantRepo) Update(data *entity.TenantResponse) (*entity.TenantResponse, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.TenantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*entity.TenantResponse) (*entity.TenantResponse, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func(*entity.TenantResponse) *entity.TenantResponse); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TenantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*entity.TenantResponse) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITenantRepo creates a new instance of ITenantRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITenantRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITenantRepo {
	mock := &ITenantRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
